# Generated by Django 5.1.4 on 2024-12-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='satus',
            new_name='status',
        ),
    ]
